# Updated to read from Docker's environment variable, falling back to localhost for local IDE runs
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/todolist}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:root}

## Hibernate Properties
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

## Hibernate Logging
logging.level.org.hibernate.SQL=DEBUG